apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: amq
  name: amq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amq
  template:
    metadata:
      labels:
        app: amq
    spec:
      containers:
      - env:
        - name: ACTIVEMQ_CONFIG_MAXMEMORY
          value: "1024"
        - name: ACTIVEMQ_CONFIG_MINMEMORY
          value: "512"
        image: webcenter/activemq:latest
        name: amq
        ports:
        - containerPort: 61616
        - containerPort: 8161
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: amq-admin
  labels:
    app: amq
spec:
  selector:
    app: amq
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8161
    targetPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: amq
  labels:
    app: amq
spec:
  selector:
    app: amq
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8162
    targetPort: 61616
