apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
  labels:
    app: es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
      - name: es 
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
        ports:
        - containerPort: 9200
        env:
        - name: discovery.type
          value: single-node
        resources: 
          requests:
            memory: "2Gi"
            cpu: "256m"
          limits:
            memory: "4Gi"
            cpu: "512m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: es
  name: es
spec:
  type: LoadBalancer
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    app: es
