apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash 
        image: docker.pkg.github.com/mmacphail/activemq-logstash-docker-image/activemq-logstash:0.0.1
        resources: 
          requests:
            memory: "256Mi"
            cpu: "256m"
          limits:
            memory: "512Mi"
            cpu: "512m"
        env:
        - name: ACTIVEMQ_BROKER_URL
          value: tcp://amq:8162
        - name: ACTIVEMQ_DESTINATION
          value: hello-world
        - name: ELASTICSEARCH_INDEX
          value: testindex
        - name: ELASTICSEARCH_URL
          value: http://es:9200
